development:
  google_client_id: 802191365888-f373g37sj0sjuv02tlvdqmvll0tmus7v.apps.googleusercontent.com
  google_client_secret: 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

production:
  google_client_id: <%= ENV["802191365888-f373g37sj0sjuv02tlvdqmvll0tmus7v.apps.googleusercontent.com"] %>
  google_client_secret: <%= ENV["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"] %>
